version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
